version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "yann"
      MYSQL_DATABASE: "timer"
  redis:
    image: redis
    ports:
      - "63790:6379"
  timer:
    image: smileleo/timer:0.1
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
      - "redis"
    links:
      - "mysql"
      - "redis"
    restart: "always"
