{
 "title": "metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(server_requests_code_total,service)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(server_requests_code_total{service=\"$Service\"},namespace)"
    }
   },
   {
    "name": "Kind",
    "label": "Kind",
    "query": {
     "query": "label_values(server_requests_code_total{service=\"$Service\", namespace=\"$Namespace\"},kind)"
    }
   },
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Quantile", "label": "Quantile", "query": "0.95,0.75,0.25" }
  ]
 },
 "panels": [
  {
   "title": "Requests QPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " rate(server_requests_code_total[$Interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "接口响应时间",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(server_requests_duration_sec_sum{service=\"$Service\",namespace=\"$Namespace\",kind=\"$Kind\"}[$Interval])/rate(server_requests_duration_sec_count{service=\"$Service\",namespace=\"$Namespace\",kind=\"$Kind\"}[$Interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "接口错误码",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(server_requests_code_total{service=\"$Service\", namespace=\"$Namespace\", kind=\"$Kind\", code=~\"40.*\"}[$Interval])",
     "legendFormat": "{{operation}}(400*)"
    },
    {
     "expr": "rate(server_requests_code_total{service=\"$Service\", namespace=\"$Namespace\", kind=\"$Kind\", code=~\"50.*\"}[$Interval])",
     "legendFormat": "{{operation}}(500*)"
    }
   ]
  },
  {
   "title": "quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($Quantile, sum(irate(server_requests_duration_sec_bucket{service=\"$Service\",namespace=\"$Namespace\",kind=\"$Kind\"}[$Interval])) by (le))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}