server:
  grpc:
    addr: 0.0.0.0:9090
    timeout_seconds: 5
  http:
    addr: 0.0.0.0:8080
    timeout_seconds: 5
data:
  database:
    driver: mysql
    source: root:yann@tcp(127.0.0.1:3306)/wikistock?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true&loc=Local
    level: 4
  redis:
    address: 127.0.0.1:6379
    read_timeout_seconds: 5
    write_timeout_seconds: 5
business:

