// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/airunny/timer/api/common"
	"github.com/airunny/timer/internal/conf"
	"github.com/airunny/timer/internal/dao"
	"github.com/airunny/timer/internal/server"
	"github.com/airunny/timer/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(serverConfig *common.ServerConfig, dataConfig *common.DataConfig, business *conf.Business, logger log.Logger) (*kratos.App, func(), error) {
	client, cleanup, err := dao.NewRedis(dataConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := dao.NewMySQL(dataConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	user := dao.NewUser(db, client)
	application := dao.NewApplication(db)
	timerRecord := dao.NewTimer(db)
	task := dao.NewTask(db)
	token := dao.NewToken(db)
	global := dao.NewGlobal(db)
	serviceService, cleanup3 := service.NewService(client, business, user, application, timerRecord, task, token, global)
	grpcServer := server.NewGRPCServer(serverConfig, serviceService, logger)
	httpServer := server.NewHTTPServer(serverConfig, serviceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
