// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: timer/v1/bucket.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BucketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfBuckets int64 `protobuf:"varint,1,opt,name=number_of_buckets,json=numberOfBuckets,proto3" json:"number_of_buckets"`
}

func (x *BucketRequest) Reset() {
	*x = BucketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_v1_bucket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketRequest) ProtoMessage() {}

func (x *BucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_bucket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketRequest.ProtoReflect.Descriptor instead.
func (*BucketRequest) Descriptor() ([]byte, []int) {
	return file_timer_v1_bucket_proto_rawDescGZIP(), []int{0}
}

func (x *BucketRequest) GetNumberOfBuckets() int64 {
	if x != nil {
		return x.NumberOfBuckets
	}
	return 0
}

type BucketReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buckets []string `protobuf:"bytes,1,rep,name=buckets,json=buckets,proto3" json:"buckets"`
}

func (x *BucketReply) Reset() {
	*x = BucketReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_v1_bucket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketReply) ProtoMessage() {}

func (x *BucketReply) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_bucket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketReply.ProtoReflect.Descriptor instead.
func (*BucketReply) Descriptor() ([]byte, []int) {
	return file_timer_v1_bucket_proto_rawDescGZIP(), []int{1}
}

func (x *BucketReply) GetBuckets() []string {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type Bucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket    string `protobuf:"bytes,1,opt,name=bucket,json=bucket,proto3" json:"bucket"`
	ServiceIp string `protobuf:"bytes,2,opt,name=service_ip,json=serviceIp,proto3" json:"service_ip"`
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_v1_bucket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_bucket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_timer_v1_bucket_proto_rawDescGZIP(), []int{2}
}

func (x *Bucket) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Bucket) GetServiceIp() string {
	if x != nil {
		return x.ServiceIp
	}
	return ""
}

type ListBucketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBucketRequest) Reset() {
	*x = ListBucketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_v1_bucket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketRequest) ProtoMessage() {}

func (x *ListBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_bucket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketRequest.ProtoReflect.Descriptor instead.
func (*ListBucketRequest) Descriptor() ([]byte, []int) {
	return file_timer_v1_bucket_proto_rawDescGZIP(), []int{3}
}

type ListBucketReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfBuckets int64     `protobuf:"varint,1,opt,name=number_of_buckets,json=numberOfBuckets,proto3" json:"number_of_buckets"`
	Buckets         []*Bucket `protobuf:"bytes,2,rep,name=buckets,json=buckets,proto3" json:"buckets"`
}

func (x *ListBucketReply) Reset() {
	*x = ListBucketReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_v1_bucket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBucketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketReply) ProtoMessage() {}

func (x *ListBucketReply) ProtoReflect() protoreflect.Message {
	mi := &file_timer_v1_bucket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketReply.ProtoReflect.Descriptor instead.
func (*ListBucketReply) Descriptor() ([]byte, []int) {
	return file_timer_v1_bucket_proto_rawDescGZIP(), []int{4}
}

func (x *ListBucketReply) GetNumberOfBuckets() int64 {
	if x != nil {
		return x.NumberOfBuckets
	}
	return 0
}

func (x *ListBucketReply) GetBuckets() []*Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_timer_v1_bucket_proto protoreflect.FileDescriptor

var file_timer_v1_bucket_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x0d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x14, 0x92, 0x41, 0x11, 0x2a, 0x0f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0xe7, 0x9a,
	0x84, 0xe4, 0xb8, 0xaa, 0xe6, 0x95, 0xb0, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f,
	0x66, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x3a, 0x0a, 0x0b, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x42, 0x11, 0x92, 0x41, 0x0e, 0x2a, 0x0c, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0xe5, 0x88, 0x97, 0xe8, 0xa1, 0xa8, 0x52, 0x07, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x22, 0x6d, 0x0a, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x29,
	0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x11,
	0x92, 0x41, 0x0e, 0x2a, 0x0c, 0xe5, 0x88, 0x86, 0xe6, 0xa1, 0xb6, 0xe5, 0x90, 0x8d, 0xe7, 0xa7,
	0xb0, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x38, 0x0a, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x19, 0x92,
	0x41, 0x16, 0x2a, 0x14, 0xe6, 0x89, 0x80, 0xe5, 0xb1, 0x9e, 0xe6, 0x9c, 0x8d, 0xe5, 0x8a, 0xa1,
	0x49, 0x50, 0xe5, 0x9c, 0xb0, 0xe5, 0x9d, 0x80, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x70, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x40, 0x0a, 0x11,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x14, 0x92, 0x41, 0x11, 0x2a, 0x0f, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0xe7, 0x9a, 0x84, 0xe4, 0xb8, 0xaa, 0xe6, 0x95, 0xb0, 0x52, 0x0f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x41,
	0x0a, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x11, 0x92, 0x41, 0x0e, 0x2a, 0x0c, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0xe5, 0x88, 0x97, 0xe8, 0xa1, 0xa8, 0x52, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x42, 0x11, 0x5a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timer_v1_bucket_proto_rawDescOnce sync.Once
	file_timer_v1_bucket_proto_rawDescData = file_timer_v1_bucket_proto_rawDesc
)

func file_timer_v1_bucket_proto_rawDescGZIP() []byte {
	file_timer_v1_bucket_proto_rawDescOnce.Do(func() {
		file_timer_v1_bucket_proto_rawDescData = protoimpl.X.CompressGZIP(file_timer_v1_bucket_proto_rawDescData)
	})
	return file_timer_v1_bucket_proto_rawDescData
}

var file_timer_v1_bucket_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_timer_v1_bucket_proto_goTypes = []interface{}{
	(*BucketRequest)(nil),     // 0: api.timer.v1.BucketRequest
	(*BucketReply)(nil),       // 1: api.timer.v1.BucketReply
	(*Bucket)(nil),            // 2: api.timer.v1.Bucket
	(*ListBucketRequest)(nil), // 3: api.timer.v1.ListBucketRequest
	(*ListBucketReply)(nil),   // 4: api.timer.v1.ListBucketReply
}
var file_timer_v1_bucket_proto_depIdxs = []int32{
	2, // 0: api.timer.v1.ListBucketReply.buckets:type_name -> api.timer.v1.Bucket
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_timer_v1_bucket_proto_init() }
func file_timer_v1_bucket_proto_init() {
	if File_timer_v1_bucket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timer_v1_bucket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_v1_bucket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_v1_bucket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_v1_bucket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBucketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_v1_bucket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBucketReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timer_v1_bucket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timer_v1_bucket_proto_goTypes,
		DependencyIndexes: file_timer_v1_bucket_proto_depIdxs,
		MessageInfos:      file_timer_v1_bucket_proto_msgTypes,
	}.Build()
	File_timer_v1_bucket_proto = out.File
	file_timer_v1_bucket_proto_rawDesc = nil
	file_timer_v1_bucket_proto_goTypes = nil
	file_timer_v1_bucket_proto_depIdxs = nil
}
